"use client";

/**
 * Artifact renderer — takes raw HTML generated by the agent and
 * renders it in a sandboxed iframe. The sandbox attribute prevents
 * the generated code from accessing cookies, localStorage, or the
 * parent page. Scripts are allowed so Plotly/Chart.js work.
 *
 * Data flow:
 *   Agent response → FastAPI strips <artifact> tags → Next.js receives
 *   html string → this component renders it in a safe iframe.
 */

interface ArtifactProps {
  html: string;
  height?: number;
}

export function Artifact({ html, height = 420 }: ArtifactProps) {
  const srcDoc = html.startsWith("<!DOCTYPE") || html.startsWith("<html")
    ? html
    : `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { margin: 0; font-family: system-ui, sans-serif; background: #fff; }
  </style>
</head>
<body>${html}</body>
</html>`;

  return (
    <div className="rounded-xl border border-gray-200 overflow-hidden shadow-sm my-3">
      <div className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 border-b border-gray-200">
        <span className="w-2.5 h-2.5 rounded-full bg-red-400" />
        <span className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
        <span className="w-2.5 h-2.5 rounded-full bg-green-400" />
        <span className="text-xs text-gray-500 ml-2 font-mono">artifact</span>
      </div>
      <iframe
        srcDoc={srcDoc}
        sandbox="allow-scripts"   // scripts on, but no same-origin, no forms, no popups
        style={{ width: "100%", height, border: "none", display: "block" }}
        title="Generated artifact"
      />
    </div>
  );
}
